services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/martin/server/apps/sonarr/data:/config
      - /home/martin/server/apps/sonarr/tvseries:/tv #optional
      - /home/martin/server/apps/sonarr/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
